apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kubectl
      image: internal-registry.tkg.mobilink.net.pk/wso2-dev/jenkins/kubectl:vsphere
      resources:
        requests:
          ephemeral-storage: "20Mi"
        limits:
          ephemeral-storage: "100Mi"
      command:
        - /bin/cat
      tty: true
      env:
        - name: KUBECTL_VSPHERE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-pass
              key: password
    - name: kaniko
      image: internal-registry.tkg.mobilink.net.pk/wso2-dev/kaniko/executor:v1.0
      resources:
        requests:
          ephemeral-storage: "1Gi"
        limits:
          ephemeral-storage: "3Gi"
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
    - name: maven
      image: internal-registry.tkg.mobilink.net.pk/wso2-dev/maven:3.8.5-orcl-jdk-11
      resources:
        requests:
          ephemeral-storage: "20Mi"
        limits:
          ephemeral-storage: "100Mi"
      command:
        - /bin/cat
      tty: true
      volumeMounts:
        - name: maven-storage
          mountPath: /root/.m2
    - name: apictl
      image: internal-registry.tkg.mobilink.net.pk/wso2-dev/wso2/apictl:v1.0
      resources:
        requests:
          ephemeral-storage: "20Mi"
        limits:
          ephemeral-storage: "100Mi"
      command:
        - /bin/cat
      tty: true
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: maven-storage
      persistentVolumeClaim:
        claimName: maven-pvc
