apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wso2
  name: <WS02_APP_NAME>-deploy-mi
  annotations:
    kubernetes.io/change-cause: "init deploy"
  labels:
    app: <WS02_APP_NAME>-mi
spec:
  selector:
    matchLabels:
      app: <WS02_APP_NAME>-mi
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0% 
  template:
    metadata:
      labels:
        app: <WS02_APP_NAME>-mi
    spec:
      containers:
        - name: <WS02_APP_NAME>-mi
          image: internal-registry.tkg.mobilink.net.pk/wso2-prod/wso2/wso2mi/<WS02_APP_NAME>:<WS02_APP_TAG> 
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JVM_MEM_OPTS
              value: "-Xms3500m -Xmx3500m"
          resources:
            requests:
              memory: "4Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          ports:
            - containerPort: 8290 # HTTP port
            - containerPort: 8253 # HTTPs port
            - containerPort: 9201 # EI_INTERNAL_HTTP
            - containerPort: 9164 # EI_INTERNAL_HTTPS
          livenessProbe:
              exec:
                  command:
                  - /bin/sh
                  - -c
                  - nc -z localhost 8290
              failureThreshold: 3
              initialDelaySeconds: 40
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
          readinessProbe:
              httpGet:
                  path: /healthz
                  port: 9201
              failureThreshold: 3
              initialDelaySeconds: 40
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
          volumeMounts:
            - name: truststore-volume
              mountPath: "/home/wso2carbon/wso2mi-4.1.0/repository/resources/security/client-truststore.jks"
              subPath: client-truststore.jks
            - name: log4j2-volume
              mountPath: /home/wso2carbon/wso2mi-4.1.0/conf/log4j2.properties
              subPath: log4j2.properties
            - name: wso2-logs-volume
              mountPath: /home/wso2carbon/wso2mi-4.1.0/repository/logs
      volumes:
        - name: truststore-volume
          secret:
            secretName: mi-client-truststore
        - name: log4j2-volume
          configMap:
            name: wso2-mi-log4j2
        - name: wso2-logs-volume
          hostPath:
            path: /wso2-logs/<WS02_APP_NAME>
            type: DirectoryOrCreate
---
apiVersion: v1 
kind: Service
metadata:
  namespace: wso2
  name: <WS02_APP_NAME>-svc-ci-mi
spec:
  selector:
    app: <WS02_APP_NAME>-mi
  ports:
    - protocol: "TCP"
      name: "http"
      port: 8290 
      targetPort: 8290 
    - protocol: "TCP"
      name: "https"
      port: 8253 
      targetPort: 8253 
    - protocol: "TCP"
      name: "ei-internal-http"
      port: 9201 
      targetPort: 9201
    - protocol: "TCP"
      name: "ei-internal-https"
      port: 9164 
      targetPort: 9164 
  type: ClusterIP 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <WS02_APP_NAME>-ing-mi
  namespace: wso2
  annotations:
    projectcontour.io/response-timeout: 90s
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - microservices.jazz.com.pk
      secretName: microservices.jazz.com.pk-tls
  ingressClassName: internal-contour
  rules:
    # - host: microservices.jazz.com.pk
    #   http:
    #     paths:
    #       - path: /ecare/loan/v1
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: <WS02_APP_NAME>-svc-ci-mi
    #             port:
    #               number: 8290
    - host: microservices.jazz.com.pk
      http:
        paths:
          - path: /ecare/loan/v2
            pathType: Prefix
            backend:
              service:
                name: <WS02_APP_NAME>-svc-ci-mi
                port:
                  number: 8290
    # - host: microservices.jazz.com.pk
    #   http:
    #     paths:
    #       - path: /ecare/loan/v1/subscribe
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: <WS02_APP_NAME>-svc-ci-mi
    #             port:
    #               number: 8290
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: <WS02_APP_NAME>-hpa-mi
  namespace: wso2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <WS02_APP_NAME>-deploy-mi
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
