[server]
hostname = "localhost"
# offset  = 6

[user_store]
type = "read_only_ldap"

[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "wso2carbon"
alias = "symmetric.key.value"
algorithm = "AES"

[transport.http]
preserve_http_user_agent=true
socket_timeout = 600000
core_worker_pool_size = 400
max_worker_pool_size = 500
worker_pool_queue_length = -1
io_buffer_size = 16384
max_http_connection_per_host_port = 32767

[passthru_http]
preserve_http_user_agent=true
http.socket.timeout= 600000
core_worker_pool_size= 400
max_worker_pool_size= 500

[mediation]
synapse.enable_xpath_dom_failover=true
synapse.core_threads = 400
synapse.max_threads = 500
synapse.global_timeout_interval = 120000
synapse.sal.endpoints.sesssion.timeout.default=600000
synapse.threads.keepalive=5
#flow.statistics.capture_all= true
#stat.tracer.collect_payloads= true
#stat.tracer.collect_mediation_properties= true


[transport.blocking.http]
sender.enable_client_caching = true
sender.transfer_encoding = "chunked"
sender.default_connections_per_host = 500

[[custom_message_formatters]]
content_type="application/vnd.api+json"
class = "org.apache.synapse.commons.json.JsonStreamFormatter"

[[custom_message_builders]]
content_type = "application/vnd.api+json"
class = "org.apache.synapse.commons.json.JsonStreamBuilder"

[[custom_message_builders]]
content_type = "text/xml"
class = "org.apache.axis2.builder.SOAPBuilder"

