[server]
hostname = "wso2-gw-a6-svc-ci"
server_role = "gateway-worker"

[user_store]
type = "database_unique_id"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://10.50.13.109:3306,10.50.13.112:3306/SHARED_DB_A?autoReconnect=true&amp;relaxAutoCommit=true&amp;useSSL=false&amp;failOverReadOnly=false"
username = "app_user"
password = "@Ws02@RC"
driver="com.mysql.cj.jdbc.Driver"

[keystore.tls]
file_name = "wso2carbon.jks"
type = "JKS"
password = "wso2carbon"
alias = "wso2carbon"
key_password = "wso2carbon"

[truststore]
file_name = "client-truststore.jks"
type = "JKS"
password = "wso2carbon"

# key manager implementation
[apim.key_manager]
service_url = "https://wso2-cp-a-svc-ci:9443/services/"
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"

[apim.sync_runtime_artifacts.gateway]
gateway_labels =["GWa6"]

# Traffic Manager configurations
[apim.throttling]
username= "$ref{super_admin.username}"
password= "$ref{super_admin.password}"
service_url = "https://wso2-cp-a-svc-ci:9443/services/"
throttle_decision_endpoints = ["tcp://wso2-cp-a-svc-ci:5672"]
enable_unlimited_tier = true
enable_header_based_throttling = false
enable_jwt_claim_based_throttling = false
enable_query_param_based_throttling = false

[[apim.throttling.url_group]]
traffic_manager_urls=["tcp://wso2-cp-a-svc-ci:9611"]
traffic_manager_auth_urls=["ssl://wso2-cp-a-svc-ci:9711"]

# Caches
[apim.cache.gateway_token]
enable = true
expiry_time = 15

[apim.cache.resource]
enable = true

[apim.cache.jwt_claim]
enable = true
expiry_time = 900

[apim.oauth_config]
remove_outbound_auth_header = true
auth_header = "Authorization"

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction"]
allow_credentials = false
